version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        user: bitnami
        ports:
            - "8000:8000"
            - "3000:3000"
            - "8080:8080"
        depends_on:
          db:
            condition: service_healthy

        environment:
          DB_CONNECTION: mysql
          DB_HOST: db
          DB_PORT: "3306"
          DB_DATABASE: compressor
          DB_USERNAME: compressor
          DB_PASSWORD: compressor
          APP_ENV: developement
          ZIP_TYPE: zip

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: compressor
            MYSQL_USER: compressor
            MYSQL_PASSWORD: compressor
            MYSQL_ROOT_PASSWORD: compressor
        ports:
            - "3306:3306"
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
